# Generated by Django 3.1.6 on 2021-07-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_auto_20210714_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
