# Generated by Django 3.1.6 on 2021-07-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_auto_20210717_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstaff',
            old_name='staffs_id',
            new_name='staff_id',
        ),
    ]
