# Generated by Django 3.1.6 on 2021-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_auto_20210723_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
