# Generated by Django 3.1.6 on 2021-08-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0010_staffs_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='fcm_token',
        ),
    ]
