# Generated by Django 3.1.6 on 2021-09-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0011_remove_staffs_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='NotificationStaff',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
